#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

REPO="yashmhatre/AgentForge"
PROJECT="agentforge-framework"
WORKFLOW="release.yml"

# Everything below reads the checkout, so run there whatever directory the
# wizard itself was started from.
REPO_DIR="${REPO_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$REPO_DIR"

# The version being released is whatever the metadata declares, and the branch
# to rehearse from is the release-prep branch for it if one exists. Read rather
# than written down, so this script outlives the release it was written for.
VERSION=$(grep -m1 '^version = ' pyproject.toml 2>/dev/null | cut -d'"' -f2 || echo "")
RELEASE_BRANCH="release/prepare-${VERSION}"
if ! git rev-parse --verify --quiet "origin/$RELEASE_BRANCH" >/dev/null 2>&1; then
  RELEASE_BRANCH="main"
fi

banner "Publish agentforge-framework: Trusted Publishers, then a rehearsal"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: what this machine and this repo already have"
say "Nothing here changes anything. It checks the things the next stages assume."
printf '\n'

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "$(printf '%s✓%s gh is installed and authenticated' "$GREEN" "$RESET")"
else
  warn "gh is missing or not authenticated. Run: gh auth login"
  SKIPPED+=("gh auth login")
fi

if gh api "repos/$REPO" --jq .full_name >/dev/null 2>&1; then
  say "$(printf '%s✓%s %s is reachable' "$GREEN" "$RESET" "$REPO")"
else
  warn "cannot reach $REPO through gh"
fi

envs=$(gh api "repos/$REPO/environments" --jq '[.environments[].name] | join(", ")' 2>/dev/null || echo "")
case "$envs" in
  *pypi*) say "$(printf '%s✓%s GitHub environments: %s' "$GREEN" "$RESET" "$envs")" ;;
  *)      warn "the pypi and testpypi environments are missing; PyPI matches on them" ;;
esac

declared="${VERSION:-?}"
say "$(printf 'This checkout declares version %s%s%s' "$BOLD" "$declared" "$RESET")"
say "$(printf 'Rehearsing from %s%s%s' "$BOLD" "$RELEASE_BRANCH" "$RESET")"

if command -v curl >/dev/null 2>&1; then
  for host in pypi.org test.pypi.org; do
    if curl -fsS -o /dev/null "https://$host/pypi/$PROJECT/json" 2>/dev/null; then
      warn "$PROJECT already exists on $host — check it is yours before uploading"
    else
      say "$(printf '%s✓%s %s is unclaimed on %s' "$GREEN" "$RESET" "$PROJECT" "$host")"
    fi
  done
else
  note "curl is not on PATH, so the name check was skipped"
fi

printf '\n'
note "Trusted Publishing means no API token is ever created, stored, or rotated."
note "The workflow presents a short-lived identity the index already trusts."
pause "Press Enter when you have read the above."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "TestPyPI: an account with 2FA"
say "TestPyPI is a separate site with separate accounts. Even if you have a"
say "PyPI login, you need one here too."
printf '\n'
open_url "https://test.pypi.org/account/register/"
step "Register, or log in if you already have a TestPyPI account."
step "Then open Account settings → Two factor authentication and enable it."
note "2FA is required before you can add a publisher."
printf '\n'
ask TESTPYPI_USER "Your TestPyPI username (for this wizard's summary only):"
pause "Press Enter once you are logged in with 2FA on."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "TestPyPI: add the pending publisher"
say "The project does not exist on TestPyPI yet, so this is a *pending*"
say "publisher: it becomes a real one the first time the workflow uploads."
printf '\n'
open_url "https://test.pypi.org/manage/account/publishing/"
step "Scroll to 'Add a new pending publisher' and pick the GitHub tab."
step "Fill it in exactly:"
printf '\n'
printf '      PyPI Project Name  %s%s%s\n' "$BOLD" "$PROJECT" "$RESET"
printf '      Owner              %s%s%s\n' "$BOLD" "${REPO%%/*}" "$RESET"
printf '      Repository name    %s%s%s\n' "$BOLD" "${REPO##*/}" "$RESET"
printf '      Workflow name      %s%s%s\n' "$BOLD" "$WORKFLOW" "$RESET"
printf '      Environment name   %s%s%s\n' "$BOLD" "testpypi" "$RESET"
printf '\n'
warn "The environment must be testpypi here. The pypi one comes later, separately."
note "Workflow name is the filename, not the 'name:' inside the file."
pause "Press Enter once TestPyPI lists the pending publisher."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Rehearse the whole path against TestPyPI"
say "This runs the Release workflow with rehearse=true. It runs the test matrix,"
say "builds the sdist and the wheel, proves the sdist carries its package data,"
say "uploads to TestPyPI, and installs it back out of the index."
printf '\n'
REF="$RELEASE_BRANCH"
if ! confirm "Rehearse from $REF?"; then
  ask REF "Which ref should it build from?"
fi
printf '\n'
if confirm "Trigger the run on $REF now?"; then
  gh workflow run "$WORKFLOW" --repo "$REPO" --ref "$REF" -f rehearse=true
  say "Dispatched. Waiting for GitHub to register the run…"
  sleep 6
  RUN_ID=$(gh run list --repo "$REPO" --workflow "$WORKFLOW" --limit 1 --json databaseId --jq '.[0].databaseId')
  say "$(printf 'Run %s%s%s: https://github.com/%s/actions/runs/%s' "$BOLD" "$RUN_ID" "$RESET" "$REPO" "$RUN_ID")"
  printf '\n'
  gh run watch "$RUN_ID" --repo "$REPO" --exit-status && REHEARSAL="passed" || REHEARSAL="failed"
else
  REHEARSAL="not run"
  SKIPPED+=("the TestPyPI rehearsal (gh workflow run $WORKFLOW -f rehearse=true)")
fi
printf '\n'
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check what TestPyPI is now serving"
if [[ "${REHEARSAL:-}" == "passed" ]]; then
  say "$(printf '%s✓%s the rehearsal passed, so OIDC, the upload, and a clean install all work' "$GREEN" "$RESET")"
else
  warn "the rehearsal ${REHEARSAL:-did not run}. Read the run log before going further:"
  note "  the usual first failure is the publisher form — owner, repo, workflow, environment"
fi
printf '\n'
open_url "https://test.pypi.org/project/$PROJECT/"
step "Confirm the version shown is the one you rehearsed."
printf '\n'
if confirm "Also install it here, in a throwaway virtualenv?"; then
  tmp=$(mktemp -d)
  python -m venv "$tmp/venv" 2>/dev/null || python3 -m venv "$tmp/venv"
  "$tmp/venv"/*/pip install --quiet --index-url https://test.pypi.org/simple/ \
    --extra-index-url https://pypi.org/simple/ "$PROJECT" &&
    "$tmp/venv"/*/agentforge --version || warn "the install from TestPyPI did not work"
  rm -rf "$tmp"
fi
printf '\n'
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "PyPI: an account with 2FA"
say "Now the real index. Same shape, different site, and this one matters:"
say "PyPI never lets a version number be reused."
printf '\n'
open_url "https://pypi.org/account/register/"
step "Register, or log in if you already have a PyPI account."
step "Account settings → Two factor authentication, if it is not on already."
printf '\n'
ask PYPI_USER "Your PyPI username (for this wizard's summary only):"
pause "Press Enter once you are logged in with 2FA on."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "PyPI: add the pending publisher"
say "Identical to the TestPyPI form, with one field changed."
printf '\n'
open_url "https://pypi.org/manage/account/publishing/"
step "'Add a new pending publisher' → GitHub tab. Fill it in exactly:"
printf '\n'
printf '      PyPI Project Name  %s%s%s\n' "$BOLD" "$PROJECT" "$RESET"
printf '      Owner              %s%s%s\n' "$BOLD" "${REPO%%/*}" "$RESET"
printf '      Repository name    %s%s%s\n' "$BOLD" "${REPO##*/}" "$RESET"
printf '      Workflow name      %s%s%s\n' "$BOLD" "$WORKFLOW" "$RESET"
printf '      Environment name   %s%s%s\n' "$BOLD" "pypi" "$RESET"
printf '\n'
warn "Environment is pypi here, not testpypi. This is the one field people get wrong."
note "Registering a pending publisher uploads nothing and claims the name for you."
pause "Press Enter once PyPI lists the pending publisher."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "What is left, and why this wizard stops here"
say "Everything reversible is done. Publishing is not reversible: PyPI never"
say "lets a version number be reused, so a bad upload burns the number rather"
say "than being a mistake you fix. That step stays yours, deliberately."
printf '\n'
step "1. Merge the release-prep PR, if one is still open."
step "2. Check CHANGELOG.md dates ${VERSION:-this release} as the day you tag."
step "3. git tag v${VERSION:-X.Y.Z} && git push origin v${VERSION:-X.Y.Z}"
step "4. Publish the GitHub release for that tag."
printf '\n'
say "Publishing the release is what runs the workflow against the real index."
say "It re-runs the test matrix, refuses if the tag and the metadata disagree,"
say "uploads, and then proves 'pip install agentforge-framework' works from a"
say "clean environment. That is #77's acceptance criterion, checked by CI."
printf '\n'
note "TestPyPI user: ${TESTPYPI_USER:-not recorded}    PyPI user: ${PYPI_USER:-not recorded}"
note "Rehearsal: ${REHEARSAL:-not run}"
pause "Press Enter for the summary."

finish
